name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - '.gitignore'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        env:
          VITE_GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}
        run: npm run build